### ISSUE TITLE
lesson date validator

### ISSUE THREAD

**Issue by marinehda** [marinehda/yoga-story#55]

**Comment by marinehda** [comment]
- lesson: maximum duration (4h)
- start date must be in the future
- end date should be dropdown of hours (0..4) and minutes (0,15,30,45)

**Comment by alexisquesney** [comment]
@marinehda 
duration => on s'en fout on blinde le formulaire pour qu'au max le user puisse choisir 4h
start_date must be in future => ok done
end_date form => @NathMeriaux je te réaffecte cette issue pour ça merci
